<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net10.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <PackageTags>$(PackageTags) rx reactive reactiveui</PackageTags>
  </PropertyGroup>

  <PropertyGroup>
    <DocumentationFile>$(ProjectDir)SharpHook.ReactiveUI.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))" />
    <PackageReference Include="ReactiveUI.Primitives" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpHook\SharpHook.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\icon.png">
      <Pack>True</Pack>
      <PackagePath />
    </None>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath />
    </None>
  </ItemGroup>

</Project>
