<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <OutputType>exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <RootNamespace>SharpHook</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FsCheck" />
    <PackageReference Include="FsCheck.Xunit.v3" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpHook\SharpHook.csproj" />
    <ProjectReference Include="..\..\src\SharpHook.R3\SharpHook.R3.csproj" />
    <ProjectReference Include="..\..\src\SharpHook.Reactive\SharpHook.Reactive.csproj" />
    <ProjectReference Include="..\..\src\SharpHook.ReactiveUI\SharpHook.ReactiveUI.csproj" />
    <ProjectReference Include="..\..\src\SharpHook.Testing\SharpHook.Testing.csproj" />
  </ItemGroup>

</Project>
